### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by diskman** [rsafier/ServiceStack.Discovery.Redis#2]
hi. I was trying to use the Plugin but have a problem on running application. Can I as on any help here @rsafier ? Eventually is there any recommendation to use different solution for Service Discovery?

```
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at ServiceStack.Discovery.Redis.RedisServiceDiscoveryFeature.TimerTick(Object state)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__27_0(Object state)
```

**Comment by rsafier** [comment]
No I haven't worked on this since it was published. you would need to update it to the latest SS framework at very least. I know at the time this feature was implemented in ServiceStack there was one other guy that built a system using Consul as the backend (ServiceStack.Discovery.Consul) looks like that hasn't been updated either. 
At the time I published this it was operating in our testing environment without issues for a few months, but never did move it to production.
